### ISSUE TITLE
Issue#02  program behaves unreliably while executing the "valkka-camsearch" command with width Parameter

### ISSUE THREAD

**Issue by Ramesh-Kesunukurthi** [elsampsa/valkka-onvif#2]
Environment: CoolerMaster-I7-RTX

Description:
Hi @elsampsa 

We are facing the following issue while executing the valkka-camsearch command with width parameter

there is a width parameter than can be sent and we know that the Imou camera at IP:158 has a H.264 sub-stream of 640x480p. When we used '640', the program could not find the RTSP URI. It also hangs sometimes. When we used '320', the program hung and we had to use the keyboard interrupt. Whenever we use '--width' parameter, the program behaves unreliably.

$valkka-camsearch --user admin --passwd L244E3F7 --width 320

Please find the attached screenshot for your reference

![valkka-width](https://github.com/elsampsa/valkka-onvif/assets/141207507/d6a11430-c005-419c-a5b0-c0e82c72d805)

**Comment by elsampsa** [comment]
pls try again with updated master branch
