### ISSUE TITLE
WSDL file update

### ISSUE THREAD

**Issue by asmeenk** [elsampsa/valkka-onvif#3]
Hi, can we get the wsdl files updated in this project? My specific issue is with DeviceIO and SendReceiveSerialCommand. This function takes a Token argument that the provided WSDL does not acknowledge. Unless I add the WSDL to the project locally and make my own class I am unable to use SendReceiveSerialCommand. Another way I found to solve the issue is to just add the token element to the SendRecieveSerialCommand element in the provided WSDL file. 

I did try simply replacing the file provided by installing the valkka-onvif package but in the wsdl:definitions section there are some directory differences that didn't allow this to simply work.

**Comment by elsampsa** [comment]
Thanks for the report.

Could you please test this one for me?

https://github.com/elsampsa/valkka-onvif/tree/master/valkka/onvif/wsdl/helper

**Comment by asmeenk** [comment]
Sorry it took so long to get back to you, we stepped away from this piece of our project for a while. We tried running this last night, the first step ran fine but is there a particular location you wanted the update script to run from? I'm not sure if it was intentional but one of the first steps is to delete the folder above where you ran the script. I'm not sure if that can work.

**Comment by elsampsa** [comment]
Nevermind - the .wsdl files have now been updated.  Also all onvif version 2.0 files are now there, so you can create custom classes using those files.
