### ISSUE TITLE
Incorrect binding name in base.py

### ISSUE THREAD

**Issue by dusvuc** [elsampsa/valkka-onvif#5]
Hello @elsampsa,

while working with your library, I noticed a bug.

In [base.py](https://github.com/elsampsa/valkka-onvif/blob/master/valkka/onvif/base.py#L171), for the `imaging` specification, we say

```
class Imaging(OnVif):
    wsdl_file = getWSDLPath("imaging-20.wsdl")
    namespace = "http://www.onvif.org/ver20/imaging/wsdl"
    sub_xaddr = "Imaging"
    port      = "ImagingPort"
```

However, the `port` value should be `ImagingBinding` - in the WDSL file (for both 1.6.6 and 1.6.5) the binding name is `ImagingBinding` (`ImagingPort` is the type). Specifically, for my ONVIF camera I'm accessing using your library, I do get:

```
Traceback (most recent call last):
  File ".../.venv/lib/python3.11/site-packages/zeep/client.py", line 133, in create_service
    binding = self.wsdl.bindings[binding_name]
              ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: '{http://www.onvif.org/ver20/imaging/wsdl}ImagingPort'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
   ---snip---
  imaging = Imaging(ip=address, port=port, user=user, password=password)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../.venv/lib/python3.11/site-packages/valkka/onvif/base.py", line 110, in __init__
    self.ws_client = self.zeep_client.create_service(self.service_addr, self.xaddr)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../.venv/lib/python3.11/site-packages/zeep/client.py", line 135, in create_service
    raise ValueError(
ValueError: No binding found with the given QName. Available bindings are: {http://www.onvif.org/ver20/imaging/wsdl}ImagingBinding
```

When I change the class in `base.py` to use `ImagingBinding` for the port value, everything works flawlessly. I can submit a PR or you can fix it yourself if it's easier for you. Thanks!

**Comment by elsampsa** [comment]
Heey.. great catch!

Let's do this the collaborative way.  Please do file a pull request. :)

**Comment by dusvuc** [comment]
Hey @elsampsa, here's the PR for the issue! I'd also ask you to update the tag once it's merged. Thanks! :)
https://github.com/elsampsa/valkka-onvif/pull/6

**Comment by elsampsa** [comment]
It's now at version 1.6.7.  Thank you.
